# Generated by Django 4.1.3 on 2022-11-11 01:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0002_product_productcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendors',
            new_name='Vendor',
        ),
    ]
