# Generated by Django 4.1.3 on 2022-11-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_alter_productrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
