# Generated by Django 4.1.3 on 2022-11-16 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_productrating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catgeory',
            new_name='category',
        ),
    ]
